### ISSUE TITLE
Cannot get spider settings

### ISSUE THREAD

**Issue by arimbr** [scrapinghub/python-scrapinghub#114]
I can set specific spider settings in the Scrapinghub UI but cannot get them with this library.

I use the spider settings to store some keys that need to match a database key, that are then used while loading the scraped data in an ETL.

I was expecting something like:
```
spider = project.spiders.get('myspider')
spider.settings()
```
or
```
spider = project.spiders.get('myspider')
spider.metadata.get('spider_settings')
```

Related issues:
Issue #84 was about accessing spider settings from the job that was possible through `job.metadata.get('job_settings')`

**Comment by vshlapakov** [comment]
Yes, you can't do that now, it's not supported. There's some internal API for getting the settings, but it's unstable and unmaintained. We have plans to rework and unify existing API later this year: when it's ready, we'll update the python bindings correspondingly.

**Comment by Gallaecio** [comment]
Closing this in favor of [the entrypoint’s `get_project_settings()`](https://github.com/scrapinghub/scrapinghub-entrypoint-scrapy/blob/3a18d1df468df9ad39044d753906c00f36a92f1b/sh_scrapy/utils.py#L5).
