### ISSUE TITLE
Get job items without _type field

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/python-scrapinghub#122]
Is there a way to download job data without `_type`?

**Comment by vshlapakov** [comment]
Could you please explain your use-case? Avoiding extra-data in response? Technically, Scrapinnghub storage returns all item fields provided on storing the item, it doesn't add the `_type` field explicitly or require the field, it's [our intermediate layer](https://github.com/scrapinghub/scrapinghub-entrypoint-scrapy/blob/master/sh_scrapy/extension.py#L46) setting the field on export step, if not set by crawler.

**Comment by manycoding** [comment]
@vshlapakov 
Since I can use `filters` I don't see any use for `_type`, and have to drop it - https://github.com/scrapinghub/arche/blob/0.3.6dev/src/arche/readers/items.py#L92

I think it would be nice if we have the option to choose what fields we want to download or what fields we want to exclude, perhaps it would be faster to do it server-side.

**Comment by vshlapakov** [comment]
> Why we add _type by default?

That's one of the core meta fields along with `_ts` and `_key`. I suppose it could be useful when you have more than one item type extracted by the same spider to filter the items. Some people use it and some others don't - I don't see any strong reason to consider removing it, the overhead is small and you can easily drop the field in your own logic.

As an option, if it really bothers you, you can always [replace](https://docs.scrapy.org/en/latest/topics/extensions.html#disabling-an-extension) the base `HubstorageExtension` with its patched version which won't set the `_type` field automatically. The sh-scrapy intermediate layer provides base classes which we maintain, and you can use your own ones if you know exactly what you want to achieve.
