### ISSUE TITLE
How to retrieve only items "_key". Is nodata supported in `items.iter()`?

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/python-scrapinghub#124]
I found an example with which I can retreive only the specified meta from job items:
https://doc.scrapinghub.com/api/items.html?highlight=metadata#examples

This could be handy to parallelize download and fix the issue with filters, collections (since we cannot properly divide items before download after `filter` is applied, or for collections which have disordered or duplicated keys) https://github.com/scrapinghub/arche/issues/13 by fetching only keys (I think it should be fast), breaking them on batches and then downloading the data.

Naturally, getting just keys should be much faster to solve the issues above. I tested locally with curl for 13kk keys:
CPU times: user 2.76 s, sys: 1.56 s, total: 4.33 s
Wall time: 9min 55s

That's not really fast, but anyway - is there `nodata`?

**Comment by vshlapakov** [comment]
The following example works fine, does it answer your question?

```
In [11]: for item in job.items.iter(nodata=True, meta=['_key']):
    ...:     print(item)
    ...: 
{u'_key': u'123/45/67/0'}
```
I suppose we should update the docs for the client :thinking:
