### ISSUE TITLE
jobs.run(spider, job_args = {arg1: val1}) can't have val1 as a list.

### ISSUE THREAD

**Issue by jdvala** [scrapinghub/python-scrapinghub#142]
I have tried to pass a list in `val1` argument and I was unable to run my spider for multiple links which I pass as an value in `job_args`. 

The way I got around that was to use `repr` to convert my list to a string and then on the spider side evaluate the string using `ast.literal_eval` and then run the spider. 

Can somebody help me with a more "scrapy" solution.

**Comment by hermit-crab** [comment]
As far as I know passing spider arguments externally (command line, ScrapyCloud API, this client) they will always be cast to plain strings and seen as such within spider. So there is no simple way to avoid serializing/deserializing explicitly the way you do it. JSON or CSV or `ast.literal_eval` would all be valid approaches. Perhaps look into https://github.com/ejulio/spider-feeder, but depending on your use case it could be an overkill.

**Comment by jdvala** [comment]
Thanks I got my answer. I will close this issue
