### ISSUE TITLE
Use stacklevel=2 on Connection warning about password usage

### ISSUE THREAD

**Issue by Gallaecio** [scrapinghub/python-scrapinghub#150]
https://github.com/scrapinghub/python-scrapinghub/blob/31be8cb248d8cb2cb70391048148e7c944dcbcca/scrapinghub/legacy.py#L66

I saw the warning in the logs, and I think a `stacklevel=2` would make it slightly more useful (although not much more, since the root issue probably comes from higher in the stack).

**Comment by vshlapakov** [comment]
Sounds good, addressed with https://github.com/scrapinghub/python-scrapinghub/commit/c70137acf2bec5f86d1eac38605dd7ffe68d1e52 :+1:
