### ISSUE TITLE
Encoding of serialization changed in version 2.3.1

### ISSUE THREAD

**Issue by TobiMayr** [scrapinghub/python-scrapinghub#151]
Encountered a breaking change after updating to version 2.3.1 from 2.3.0 while using the ScrapinghubClient to obtain items from a job. The response is not decoded to UTF-8 anymore and broke our code.

[https://github.com/scrapinghub/python-scrapinghub/compare/2.3.0...2.3.1#diff-f993fb71a6b64f99f11314f1b1e960adL28](https://github.com/scrapinghub/python-scrapinghub/compare/2.3.0...2.3.1#diff-f993fb71a6b64f99f11314f1b1e960adL28)

The change:
```
old: unpacker = Unpacker(encoding='utf8')
new: unpacker = Unpacker()
```

Is this going to be reverted in a future update? Why was this changed?

**Comment by vshlapakov** [comment]
The issue is related with updating msgpack dependency, `2.3.1` requires `msgpack>=1.0.0` which has [some internal API changes](https://github.com/msgpack/msgpack-python#major-breaking-changes-in-msgpack-10). Updating `msgpack` dependency should resolve it.

**Comment by TobiMayr** [comment]
Thank you! Updating `msgpack` did the trick
