### ISSUE TITLE
Run a specific version of a spider

### ISSUE THREAD

**Issue by gillouche** [scrapinghub/python-scrapinghub#157]
Hello,

the Job API doesn't seem to support the possibility to run a specific version of a spider. 

[Versioning](https://support.zyte.com/support/solutions/articles/22000204254-versioning-your-deploys-to-zyte-developer-tool-scrapy-cloud) is possible but the [run job API](https://docs.zyte.com/scrapy-cloud/jobs.html) has no arguments related to a version so I guess only the last one is started.

If it is correct, would it be possible to add this functionality? If not, could you please link me some documentation or code example on how to do it?

Thank you very much.

**Comment by Gallaecio** [comment]
It is correct that you can only run the latest version at the moment, and while it sounds like a reasonable feature request to me, it’s not something that can be implemented in this specific project (python-scrapinghub), it needs to be first implemented in the Job API, so an issue ticket here is probably not the right way to channel such a feature request.

**Comment by gillouche** [comment]
Alright, thanks for the quick answer.

Would you know the best way for a feature request like this one? Another project on scrapinghub's Github, a form like this [one](https://www.zyte.com/talk-to-us/) maybe?

Thanks.

**Comment by Gallaecio** [comment]
I believe the right channel is opening a [customer support](https://support.zyte.com/) ticket.
