### ISSUE TITLE
Some imports from standard lib collections are breaking on python 3.10

### ISSUE THREAD

**Issue by lbmendes** [scrapinghub/python-scrapinghub#160]
Hi everyone,

Based on an issue from another repo (https://github.com/okfn-brasil/querido-diario/issues/502), I noticed that scrapinghub is using some imports from standard lib collections that are deprecated and not working on Python 3.10.

In Python 3.8 I have these results on ipython console:
~~~python
In [1]: from collections import Iterator
<ipython-input-1-4fb967d2a9f8>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Iterator

In [2]: from collections import Iterable
<ipython-input-2-c0513a1e6784>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Iterable

In [3]: from collections import MutableMapping
<ipython-input-3-069a7babadbf>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import MutableMapping
~~~

According to this, it is necessary to change the imports of Iterable, Iterator and MutableMapping to get these items from "collections.abc" instead of just "collections"

Here are the list of imports that I found:
 - tests/client/test_job.py - from collections import Iterator
 - tests/client/test_frontiers.py - from collections import Iterable
 - tests/client/test_projects.py - from collections import defaultdict, Iterator
 - scrapinghub/hubstorage/resourcetype.py - from collections import MutableMapping

**Comment by Gallaecio** [comment]
Fixed by https://github.com/scrapinghub/python-scrapinghub/pull/166 and released in 2.4.0.
