### ISSUE TITLE
Adding a tag actually replaces all existing tags with the new.

### ISSUE THREAD

**Issue by jfeldstein** [scrapinghub/python-scrapinghub#17]
I pull jobs lacking the consumed tag:

```
jobs = sh.jobs project: '4024', state: 'finished', lacks_tag: 'consumed'
```

Jobs when pulled, are tagged with "consumed":

```
`curl -u #{ENV['SCRAPINGHUB_API_KEY']}: https://dash.scrapinghub.com/api/jobs/update.json -d project=4024 -d job=#{job['id']} -d add_tag=consumed`
```

When I respond to the pulled data, they're tagged with approved or rejected: 

```
`curl -u #{ENV['SCRAPINGHUB_API_KEY']}: https://dash.scrapinghub.com/api/jobs/update.json -d project=4024 -d job=#{job['id']} -d add_tag=approved`
```

But, after being tagged with approved or rejected, jobs lose their consumed tag, and are again returned when querying for jobs missing the consumed tag. 

```
jobs = sh.jobs project: '4024', state: 'finished', lacks_tag: 'consumed'
```

How is this aspect of the API meant to be used?

**Comment by vshlapakov** [comment]
Apologizes for so late reply. I believe this is issue is no more actual, a lot of things were changed during last year with releasing `v2.0`. The recommended way of working with tags is described [here](https://python-scrapinghub.readthedocs.io/en/latest/client/overview.html#updating-tags).
