### ISSUE TITLE
No default timeout for HTTP calls

### ISSUE THREAD

**Issue by redapple** [scrapinghub/python-scrapinghub#19]
Looks like python-requests uses `timeout=None` by default.
Calls to the API can hang a long time (forever?)

It would be helpful to add a [timeouts](http://docs.python-requests.org/en/latest/user/advanced/?highlight=timeout#timeouts) for GET and POST calls

**Comment by dangra** [comment]
:+1:

**Comment by dangra** [comment]
fixed by #94
