### ISSUE TITLE
Support for new Scrapinghub API

### ISSUE THREAD

**Issue by Nick-G** [scrapinghub/python-scrapinghub#21]
Current version of python-scrapinghub supports old API http://doc.scrapinghub.com/oldapi.html.
It would be nice to add support to new API - http://doc.scrapinghub.com/api.html. Are there any other libs that work with new API version? If not, I can work on this issue and create Pull Request to this lib.

**Comment by redapple** [comment]
@chekunkov , @vshlapakov , I believe this one can be closed now that v2.0 is out.

**Comment by vshlapakov** [comment]
@redapple Agree, it's a good time to clean opened issues.
