### ISSUE TITLE
iter behaving like list?

### ISSUE THREAD

**Issue by JamesRitchie** [scrapinghub/python-scrapinghub#76]
Based on the [description](https://python-scrapinghub.readthedocs.io/en/latest/client/apidocs.html#module-scrapinghub.client.items) in the docs, I'd expect the `iter` method on `Items` to instantly return a generator, then perform network requests as `next` is called on it, a bit like a MongoDB cursor. But instead it blocks whilst performing a lot of network activity and using substantial amounts of memory before returning the generator, which suggests it's loading the entire collection of items in the background, and is more like how I'd expect the `list` method to work. Is this correct? If this is how `iter` is supposed to work, this means it's almost impossible to work with even moderately large collections of scraped items.

**Comment by vshlapakov** [comment]
Thanks for the report and apologises for delay, I was busy with other projects and it's a shame that we missed the issues somehow. There was a hidden bug, should be fixed in master, I'll release a patch tomorrow.
