### ISSUE TITLE
Obtaining error messages

### ISSUE THREAD

**Issue by caudilldk** [scrapinghub/python-scrapinghub#77]
Based upon the documentation I have read, I don't see anything for obtaining error messages when there are errors from executing a spider.  Did I overlook something?

**Comment by ittailup** [comment]
+1 Documentation is crazy outdated.

Scrapinghubclient is now HubstorageClient

client.projects.list() is not a working command. ie 2/2 of the starting commands are broken.

**Comment by ittailup** [comment]
@redapple

**Comment by ittailup** [comment]
The documentation is depressingly out of date, no commands work as documented.

**Comment by vshlapakov** [comment]
You have access to job logs, and there's an option to filter logs by log level, check [this section](https://python-scrapinghub.readthedocs.io/en/latest/client/apidocs.html#scrapinghub.client.logs.Logs). 
Sorry for the late reply, please reopen the issue if there're any other related questions.
