### ISSUE TITLE
'Items' object is not callable

### ISSUE THREAD

**Issue by ijharulislam** [scrapinghub/python-scrapinghub#79]
I am using python scrapinghub. Now I am facing two problems. 
1. I am getting en error.

```
Traceback (most recent call last):
  File "shop_info/test.py", line 58, in <module>
    for item in job.items():
TypeError: 'Items' object is not callable
```

2. I want to pass a JSON object as an argument. I tried with this.
project.jobs.run('shop_info', job_args={'input_data': input_data})

input_data is a json object.

**Comment by spookyUnknownUser** [comment]
I think this is supposed to be 
`job.items.iter()`

According to the pydoc
```
    - retrieve all scraped items from a job::

        >>> job.items.iter()
        <generator object mpdecode at 0x10f5f3aa0>
```

Seems like this wasn't updated in the quickstart.

**Comment by ijharulislam** [comment]
Thank you for answer. I already fixed the issue with items.iter().

**Comment by vshlapakov** [comment]
Thanks :+1:
