### ISSUE TITLE
count=1 doesn't limit item count when iter/list invoked on scrapinghub.client.jobs.Job object 

### ISSUE THREAD

**Issue by gulbinas** [scrapinghub/python-scrapinghub#89]
http://python-scrapinghub.readthedocs.io/en/2.0.1/client/apidocs.html#module-scrapinghub.client.items

```
>>> job = client.get_job('XXXXX')
>>> len(list(job.items.iter(count=1)))
6021
>>> len(list(job.items.list(count=1)))
6021
```

**Comment by vshlapakov** [comment]
Thanks for the report and sorry for the delay @gulbinas.
Should be fixed in master, I'll release a patch tomorrow.
