### ISSUE TITLE
Cannot run Spiders from Script 

### ISSUE THREAD

**Issue by xavierdurandsmet** [scrapinghub/python-scrapinghub#92]
Hi,

I have a scrapy project which works great. I am trying to migrate it to ScrapingHub.
I want to be able to launch spiders from a script (see code below), but it is not working. (not accessing the Spider parse() function):

SCRIPT:
def main():
...
   yield crawler.crawl(quotes_spider.QuotesSpider)
   crawler.start()

Is it possible to do it this way? If so, how? If not, how can I run a script which calls Spiders?

Thank you

**Comment by vshlapakov** [comment]
Hi @xavierdurandsmet, you should use Scrapinghub API to launch a spider, there're 2 options:
- doing requests to HTTP API described [here](https://doc.scrapinghub.com/api/jobs.html) (for example with [requests](https://github.com/requests/requests))
- relying on the official python client, take a look at [the documentation](https://python-scrapinghub.readthedocs.io/en/latest/client/overview.html#running-jobs)
So what you need to do basically is modify your script as proposed, add additional dependencies into your `requirements.txt` (if any) and redeploy to Scrapy Cloud.

**Comment by vshlapakov** [comment]
I'm going to close this for now, please reopen the issue it doesn't respond to your questions.
