### ISSUE TITLE
class for job's key

### ISSUE THREAD

**Issue by iAnanich** [scrapinghub/python-scrapinghub#95]
I have written `JobKey` class that represents the key to the job on ScrapingHub service in `project_id/spider_id/job_number` format. Also, it offers methods to quickly get an ID of the spider/project, tuple representation, etc.

You can find it' code [here](https://github.com/iAnanich/scrapy-ntk/blob/v1.9.0/scrapy_ntk/scraping_hub/job.py#L15).

Maybe it can be somehow modified/improved to get included into `python-scrapinghub` library?

**Comment by vshlapakov** [comment]
Hi @iAnanich, first of all thanks for sharing.

We had something like this in mind when designing changes for v2, but decided to keep it as simple as possible by having only `project_id` & `key` as `Job` attributes. The reason behind this decision is that in most cases:
- you don't need a separate `spider_id`, instead you get a `Spider` instance by name and work with it
- you don't need a separate `job_id`, instead you can get a `Job` instance by full job key and use it
- to get a list/tuple, it looks easier to just split a string key than search for a custom method in library

You probably saw `JobKey` class in the utils, but it's used only internally for validation, it's not something returned to clients. And after all there's also [a helper](https://github.com/scrapinghub/python-scrapinghub/blob/master/scrapinghub/client/utils.py#L46-L66) to parse & validate a given job key - that's pretty much we use in the client, and to be honest I don't think we want to complicate the logic.
