### ISSUE TITLE
Able to use items.iter() start argument with same project_id/spider_id but different job_id

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/python-scrapinghub#97]
```
from scrapinghub import ScrapinghubClient

c = ScrapinghubClient(api_key)
[item for item in c.get_job("312967/1/7").items.iter(count=100, start="312967/1/3/1")]
```

This one returns items from '312967/1/3' while in my opinion the iter should fail because the job keys are different.

**Comment by vshlapakov** [comment]
Thanks for the report, it's clearly a minor inconsistency bug. The python client should validate `start` and `start_after` parameters where a user can pass an entity id belonging to a different job, this is true for items/logs/requests entities (the ones the user has to). PR is welcome if you have time for this.

**Comment by mehmetboraezer** [comment]
Hi, I read this issue and tested it. Then I found a different bug but it seems related to this.

I use my own api-key and **319386** is my test project id. I try to iterate different project with this **319110** id. Normally api should be returned **unauthorized** response but api return different user data to me. It seems critical. What do you think? 

```
from scrapinghub.client import ScrapinghubClient

api_key = 'ABC'

c = ScrapinghubClient(api_key)

[item for item in c.get_job("319386/1/7").items.iter(count=2, start="319110/1/3/1")]

[{u'_cached_page_id': u'9697634111876a4b1e894895de15a40c970f866e',
  u'_template': u'752d-4a7e-8eff',
  u'_type': u'EDESIX VB- VIDEO BADGE1',
  u'fulltree': [u'Home / Categories'],
  u'title1': [u'Categories'],
  u'title2': [u'Categories'],
  u'tree1': [u'http://www.videosecurityproducts.com.au/'],
  u'tree2': [u'http://www.videosecurityproducts.com.au/'],
  u'tree3': [u'http://www.videosecurityproducts.com.au/'],
  u'url': u'http://www.videosecurityproducts.com.au/category'},
 {u'_cached_page_id': u'18167e0425bf4781fc5f162754be2cd1af7bc59c',
  u'_template': u'752d-4a7e-8eff',
  u'_type': u'EDESIX VB- VIDEO BADGE1',
  u'fulltree': [u'Home / TVI CCTV / HIKVISION'],
  u'title1': [u'HIKVISION'],
  u'title2': [u'HIKVISION'],
  u'tree1': [u'http://www.videosecurityproducts.com.au/'],
  u'tree2': [u'http://www.videosecurityproducts.com.au/category/389-tvi-cctv'],
  u'tree3': [u'http://www.videosecurityproducts.com.au/category/389-tvi-cctv'],
  u'url': u'http://www.videosecurityproducts.com.au/category/477-hikvision'}]
```

**Comment by vshlapakov** [comment]
@mehmetboraezer Hi, thanks for checking. I can't reproduce it though with my own test projects and the project with id 319110 doesn't exit. The issue mentioned here allows you to get data from different project **you have access to**, not to any project (a target project should belong to your org/user, or your org/user should be a member of the project).

**Comment by manycoding** [comment]
As per conversation with @vshlapakov this should be fixed on REST API side.
